spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gugu
    username: root
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        highlight_sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      password:

app:
  jwt:
    secret-key: secret
    access-token-expiration: 43200 # 30분
    refresh-token-expiration: 43200 # 30일